version: '3'
services:
  postgres1:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      #POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      #POSTGRES_DB: fav_test2
    ports:
      - "5433:5432"
    volumes:
      - data2:/var/lib/postgresql/data

  products:
    build: ./products
    ports:
      - "5000:5000"
    depends_on:
      - postgres1

  favorites:
    build: ./favorites
    ports:
      - "5001:5001"
    depends_on:
      - postgres2

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - products
      - favorites

#volumes:
#  postgres1:
#    driver: local
#  postgres2:
#    driver: local

volumes:
  data:
  data2: