version: "3"
services:
  products-db:
    image: postgres:16.0
    container_name: products
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products
    volumes:
      - products-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

  favorites-db:
    image: postgres:16.0
    container_name: favorites
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fav_test2
    volumes:
      - favorites-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my_network


#  products-app:
#    build:
#      context: ./products
#      dockerfile: Dockerfile
#    ports:
#      - "5001:5001"  # Assuming your products Flask app listens on port 5000
#    networks:
#      - my_network
#    depends_on:
#      - products-db
#
#  favorites-app:
#    build:
#      context: ./favorites
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"  # Assuming your products Flask app listens on port 5000
#    networks:
#      - my_network
#    depends_on:
#      - favorites-db
#      - products-app

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Assuming your Go gateway listens on port 80
    networks:
      - my_network
    #depends_on:
     # - products-app
     # - favorites-app

volumes:
  products-data:
  favorites-data:

networks:
  my_network:
    driver: bridge